In [37]:
import numpy as np

depth = 5
width = 3 # = height

# We create the 3D matrix
m = np.zeros((depth, width, width))

# The last column on every depth is [0, 1, 2]
last_column = np.arange(width)
m[:, :, 2] += last_column

# The middle column on every depth is [0, ..., 1, ..., 2]
middle_column = np.arange(depth)
m[:, :, 1] += middle_column[:, None] # <- the `None` here is a bit tricky. This what we call broadcasting

print(m)

[[[0. 0. 0.]
  [0. 0. 1.]
  [0. 0. 2.]]

 [[0. 1. 0.]
  [0. 1. 1.]
  [0. 1. 2.]]

 [[0. 2. 0.]
  [0. 2. 1.]
  [0. 2. 2.]]

 [[0. 3. 0.]
  [0. 3. 1.]
  [0. 3. 2.]]

 [[0. 4. 0.]
  [0. 4. 1.]
  [0. 4. 2.]]]


## Broadcast

How does broadcasting works ? It is a bit complicated to understand. You can think of this as:
"I broadcast when I want to expand my vector along a particular dimension"

### Example

In [38]:
# we have a 2d matrix

m = np.reshape(np.arange(15), (3, 5))
print(m)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [39]:
# We want to had the vector [10, 11, 12, 13, 14] on every row.

# Naive algorithm, which consists in iterating over all the rows
m = np.reshape(np.arange(15), (3, 5))
vector = np.array([10, 11, 12, 13, 14])
for row in m:
    row += vector
print(m)

[[10 12 14 16 18]
 [15 17 19 21 23]
 [20 22 24 26 28]]


In [40]:
# Let's use broadcasting. Basically, we want "to expand along the row", so we introduce the `None` dimension on the row

m = np.reshape(np.arange(15), (3, 5))
vector = np.array([10, 11, 12, 13, 14])
m += vector[None, :]
print(m)

[[10 12 14 16 18]
 [15 17 19 21 23]
 [20 22 24 26 28]]


## Performance comparisons

Let's try with a very tall matrix, with 1 million rows.

In [47]:
from time import time

height, width = 1_000_000, 5

m = np.reshape(np.arange(height*width), (height, width))
vector = np.array([10, 11, 12, 13, 14])
beginning_time = time()
for row in m:
    row += vector
elapsed_time_iterating = time() - beginning_time
print("{:.4f}s elapsed with the iterating method".format(elapsed_time_iterating))


m = np.reshape(np.arange(height*width), (height, width))
vector = np.array([10, 11, 12, 13, 14])
beginning_time = time()
m += vector[None, :]
elapsed_time_broadcasting = time() - beginning_time
print("{:.4f}s elapsed with the broadcasting method".format(elapsed_time_broadcasting))
print("Broadcasting is {:.4f}x faster".format(elapsed_time_iterating / elapsed_time_broadcasting))

0.6077s elapsed with the iterating method
0.0130s elapsed with the broadcasting method
Broadcasting is 46.9100x faster
